NutriFood/NutriFood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('search/', include('search.urls')),
    path('admin/', admin.site.urls),
]

NutriFood/search/urls.py
from django.urls import path

from . import views

# Create namespace for the application
app_name = "search"

urlpatterns = [
    # Path: /search/
    path('', views.index, name='index'),
    # Path: /search/compare/
    # Referring to view "product_compare" in /search/views.py
    # Be careful to the order of the paths to avoid wrong referencing due to the more generic pattern
    # Here product_compare won't work if below product detail
    path('compare/', views.product_compare, name='product_compare'),
    # Path: /search/<product_id>/
    # Referring to view "product_detail" in /search/views.py
    path('<str:product_id>/', views.product_detail, name='product_detail'),

]

NutriFood/search/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    _DATABASE = 'default'
    id = models.CharField(max_length=13, primary_key=True)
    category = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    nutriscore_grade = models.CharField(max_length=1)
    nutriscore_score = models.SmallIntegerField(blank=True, null=True)
    product_name = models.CharField(max_length=100)

    class Meta:
        db_table = 'product'

NutriFood/search/views.py
from django.shortcuts import render
from .models import Product
from django.http import HttpResponse

# Create your views here.

def index(request):
    product_all = Product.objects.all()
    context = {"product_all": product_all}
    return render(request, "search/index.html", context)


# Product_id is extracted from the URL matching the "product_detail" pattern in search/urls.py
def product_detail(request, product_id):
    # Access "Product" object database and get records from the URL product_id
    product = Product.objects.get(id=product_id)
    # Dictionary holding data to pass to the template, here product records for the given product_id
    context = {"product": product}
    # Render function takes the request, the template path, and the context dictionary as arguments
    # This function combines the template with the provided context data and generates an HTML response, which is sent back to the client.
    return render(request, "search/product_detail.html", context)


def product_compare(request):
    distinct_categories = Product.objects.values('category')\
        .distinct()\
        .order_by('category')
    if request.method == 'POST':
        selected_category = request.POST.get('category')
        selected_product = request.POST.get('product_name')
        related_products = Product.objects.filter(category=selected_category)\
            .order_by('product_name')
        alternative_products = Product.objects.filter(category=selected_category)\
            .order_by('nutriscore_score')[:5]
        try:
            product_info = Product.objects.get(product_name=selected_product)
        except Product.DoesNotExist:
            product_info = None
        context = {
            "product_info": product_info,
            "related_products": related_products,
            "distinct_categories": distinct_categories,
            "selected_category": selected_category,
            "alternative_products": alternative_products,
            "selected_product": selected_product
        }
        return render(request, "search/product_compare.html", context)
    else:
        selected_category = request.GET.get('category')  # Get the selected category from the query parameters
        related_products = Product.objects.filter(category=selected_category) \
            .order_by('product_name')
        context = {
            "related_products": related_products,
            "distinct_categories": distinct_categories,
            "selected_category": selected_category,
    }
        return render(request, "search/product_compare.html", context)

NutriFood/search/templates/search/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Product List</title>
</head>
<body>
<!--
Simple curly brackets are used for template tags and filters.
They provide additional functionality, such as control structures (if statements, loops),
filtering data, or executing specific template-related tasks.
-->
{% if product_all %}
    <ul>
    {% for product in product_all %}
        <li><p> {{ product.id }}: {{ product.product_name }}</p></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No product in database.</p>
{% endif %}
</body>

NutriFood/search/templates/search/product_compare.html
<!DOCTYPE html>
<html>
<head>
    <title>Product Compare</title>
</head>
<body>
    <h1>Select a product</h1>
    <!--
    # Select a product category from the DB
    # Select a product name based on category
    # Display select product data
    # Provide a list of 5 alternative in the same category from views

    -->

    <!-- Refer to URL product compare in search application => be sure to name application in urls.py of the app -->
    <form action="{% url 'search:product_compare' %}" method="post" id="product-compare-form">
        <!-- (Cross-Site Request Forgery) token => security measure to protect against malicious form submissions -->
        {% csrf_token %}
        <fieldset>
            <legend><h1>Select category and product</h1></legend>
            <!-- onchange event allow to trigger a form submit to get the product names -->
            <select name="category" id="category-select" onchange="this.form.submit()">
                {% for category in distinct_categories %}
                <!--
                value="{{ category.category }}": The value attribute specifies the value that will be submitted to the server when this option is selected

                category.category: is the actual display text for the category
                {% if selected_category == category.category %} selected {% endif %}: selected value persists
                -->
                <option value="{{ category.category }}" {% if selected_category == category.category %} selected {% endif %}>
                    {{ category.category }}
                </option>
                {% endfor %}
            </select>

            <select name="product_name" id="product-select">
                {% if selected_category %}
                    {% for product in related_products %}
                    <option value="{{ product.product_name }}" {% if selected_product == product.product_name %} selected {% endif %}>
                        {{ product.product_name }}
                    </option>
                    {% endfor %}
                {% endif %}
            </select>
        </fieldset>
        <br>
        <input type="submit" value="Search">
    </form>

    <br>
    {% if selected_product %}
    <p>Product ID: {{ product_info.id }}</p>
    <p>Category: {{ product_info.category }}</p>
    <p>Brand: {{ product_info.brand }}</p>
    <p>Nutriscore Grade: {{ product_info.nutriscore_grade }}</p>
    <p>Nutriscore Score: {{ product_info.nutriscore_score }}</p>
    <p>Product Name: {{ product_info.product_name }}</p>
    {% endif %}
    <br>

    {% if related_products %}
    <h2>Top 5 alternative products with a better nutriscore:</h2>
    <ul>
        {% for product in alternative_products %}
            <li>
                <p>Product ID: {{ product.id }} /
                    Category: {{ product.category }} /
                    Brand: {{ product.brand }} /
                    Nutriscore Grade: {{ product.nutriscore_grade }} /
                    Nutriscore Score: {{ product.nutriscore_score }} /
                    Product Name: {{ product.product_name }}</p>
            </li>
        {% endfor %}
    </ul>
{% endif %}


</body>

NutriFood/search/templates/search/product_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Product Detail</title>
</head>
<body>
    <h1>Product Detail</h1>
    <!-- Double curly brackets are used for variables -->
    <p>Product ID: {{ product.id }}</p>
    <p>Category: {{ product.category }}</p>
    <p>Brand: {{ product.brand }}</p>
    <p>Nutriscore Grade: {{ product.nutriscore_grade }}</p>
    <p>Nutriscore Score: {{ product.nutriscore_score }}</p>
    <p>Product Name: {{ product.product_name }}</p>
</body>
</html>